### ISSUE TITLE
Not working in Craft 2.5

### ISSUE THREAD

**Issue by johneemac** [boboldehampsink/reverserelations#2]
Hi,

This doesnt seem to be woring in Craft version 2.5.
Error:

Internal Server Error
CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sources1.sortOrder' in 'order clause'

**Comment by timkelty** [comment]
@johneemac Until this is merged, you can use the changes in my fork for this to work in 2.5.
